@c -*-texinfo-*-

@node crypto
@section Cryptographic primitives

Beware that if you're using some of these libraries for sensitive
data, let's say passwords, then there is probably no way to make sure
a password is ever gone from memory. There is no guarantee that the
passwords will not be swapped out to disk or transmitted by radio.
There might be other problems as well. The algorithms themselves might
be weak. Don't pick weak keys. Know what you're doing.

Your Scheme's implementation of @code{(srfi :27 random-bits)} might be
too weak. It's common that it will be initialized from time alone, so
an attacker can easily guess your @code{random-source} internal state
by trying a few timestamps and checking which one generates the data
you sent. These libraries try to use @code{/dev/urandom} if it exists,
but if it doesn't they fall back on SRFI-27 and could reveal the
secret of your heart to the enemy. See RFC4086 for details on how
randomness works.
@cindex randomness
@cindex entropy

And remember what the license says about warranties. Don't come crying
to me if the enemy deciphers your secret messages and your whole
convoy blows up. These libraries have not been validated by the NIST
or the FDA and quite likely aren't allowed for government work.
@cindex security, warning

@menu
* crypto aes::         Advanced Encryption Standard
* crypto blowfish::    The Blowfish cipher
* crypto crc::         Cyclic Redundancy Codes
* crypto des::         Data Encryption Standard
* crypto dsa::         Digital Signature Algorithm
* crypto md5::         Message-Digest algorithm 5
* crypto password::    Password hashing
* crypto sha-1::       Secure Hash Algorithm 1
* crypto sha-2::       Secure Hash Algorithm 2
@end menu

@c ======================================================================
@node crypto aes
@subsection Advanced Encryption Standard
The @code{(weinholt crypto aes)} library provides an implementation of
the symmetrical Rijndael cipher as parameterized by the Advanced
Encryption Standard (AES). It was created by the Belgian
cryptographers Joan Daemen and Vincent Rijmen. Key lengths of 128, 192
and 256 bits are supported.

The code uses clever lookup tables and is probably as fast as any
@rnrs{} implementation of AES can be without using an FFI. The number
of modes provided is pretty sparse though (only ECB and CTR). It also
leaks key material via memory.

@deffn Procedure expand-aes-key key
Expands the @var{key} into an @dfn{AES key schedule} suitable for
@code{aes-encrypt!}. The @var{key} must be a bytevector of length 16,
24 or 32 bytes. The type of the return value is unspecified.
@end deffn

@deffn Procedure aes-encrypt! source source-start target target-start key-schedule
Takes the 16 bytes at @var{source}+@var{source-start}, encrypts
them in Electronic Code Book (ECB) mode using the given
@var{key-schedule}, and then writes the result at
@var{target}+@var{target-start}. The @var{source} and the @var{target}
can be the same.

@example
(import (weinholt crypto aes))
(let ((buf (string->utf8 "A Scheme at work"))
      (sched (expand-aes-key (string->utf8 "super-secret-key"))))
  (aes-encrypt! buf 0 buf 0 sched)
  buf)
@result{} #vu8(116 7 242 187 114 235 130 138 166 39 24 204 117 224 5 8)
@end example

It is generally not a good idea to use ECB mode alone.
@end deffn

@deffn Procedure reverse-aes-schedule key-schedule
Reverses the @var{key-schedule} to make it suitable for @code{aes-decrypt!}.
@end deffn

@deffn Procedure aes-decrypt! source source-start target target-start key-schedule
Performs the inverse of @code{aes-encrypt!}. The @var{key-schedule}
should first be reversed with @code{reverse-aes-schedule}.

@example
(import (weinholt crypto aes))
(let ((buf (bytevector-copy #vu8(116 7 242 187 114 235 130 138
                                 166 39 24 204 117 224 5 8)))
      (sched (reverse-aes-schedule 
              (expand-aes-key 
               (string->utf8 "super-secret-key")))))
  (aes-decrypt! buf 0 buf 0 sched)
  (utf8->string buf))
@result{} "A Scheme at work"
@end example
@end deffn

@deffn Procedure clear-aes-schedule! key-schedule
Clears the AES key schedule so that it no longer contains
cryptographic material. Please note that there is no guarantee that
the key material will actually be gone from memory. It might remain in
temporary numbers or other values.
@end deffn

@deffn Procedure aes-ctr! source source-start target target-start len key-schedule ctr
Encrypts or decrypts the @var{len} bytes at
@var{source}+@var{source-start} using Counter (CTR) mode and writes
the result to @var{target}+@var{target-start}. The @var{len} does not
need to be a block multiple. The @var{ctr} argument is a non-negative
integer.

This procedure is its own inverse and the @var{key-schedule} should
not be reversed for decryption.

Never encrypt more than once using the same @var{key-schedule} and
@var{ctr} value. If you're not sure why that is a bad idea, you should
read up on CTR mode.
@end deffn

@noindent
Version history:
@itemize
@item
@code{(1 0)} -- Initial version.
@end itemize

@c ======================================================================
@node crypto blowfish
@subsection The Blowfish Cipher
The @code{(weinholt crypto blowfish)} library is a complete
implementation of Bruce Schneier's Blowfish cipher. It is a symmetric
block cipher with key length between 8 and 448 bits. The key
length does not affect the performance.

@deffn Procedure expand-blowfish-key key
Expands a Blowfish @var{key}, which is a bytevector of length between
1 and 56 bytes (the longer the better). The returned key schedule can
be used with @code{blowfish-encrypt!} or
@code{reverse-blowfish-schedule}.
@end deffn

@deffn Procedure blowfish-encrypt! source source-index target target-index schedule
Encrypts the eight bytes at @var{source}+@var{source-start} using
Electronic Code Book (ECB) mode. The result is written to
@var{target}+@var{target-start}.
@end deffn

@deffn Procedure reverse-blowfish-schedule
Reverses a Blowfish key schedule so that it can be used with
@code{blowfish-decrypt!}.
@end deffn

@deffn Procedure blowfish-decrypt! source source-index target target-index schedule
The inverse of @code{blowfish-encrypt!}.
@end deffn

@deffn Procedure clear-blowfish-schedule!
Clears the Blowfish key schedule so that it no longer contains
cryptographic material. Please note that there is no guarantee that
the key material will actually be gone from memory. It might remain in
temporary numbers or other values.
@end deffn

@noindent
Version history:
@itemize
@item
@code{(0 0)} -- Initial version.
@end itemize

@c ======================================================================
@node crypto crc
@subsection Cyclic Redundancy Codes
The @code{(weinholt crypto crc)} library exports syntax for defining
procedures that calculate CRCs. There is a simple syntax that simply
requires the name of the CRC, and an advanced syntax that can define
new CRCs.

CRCs do not really qualify as cryptography, because it is trivial to
modify data so that the modified data's CRC matches the old one.

@deffn Syntax define-crc name
This is the simple interface that requires merely the name of the CRC
algorithm. The pre-defined CRCs that can be used this way are currently:
@code{crc-32}, @code{crc-16}, @code{crc-16/ccitt}, @code{crc-32c},
@code{crc-24} and @code{crc-64}.

@example
(import (weinholt crypto crc))
(define-crc crc-32)
@end example
@end deffn

@deffn Syntax define-crc name width polynomial init ref-in ref-out xor-out check
For details on how the arguments work, and the theory behind them, see
Ross N.@tie{}Williams's paper @cite{A painless guide to CRC error
detection algorithms}, which is available at
@url{http://www.ross.net/crc/crcpaper.html}. A brief description of the
arguments follows.

The @var{width} is the bitwise length of the polynomial. You might be
led to believe that it should sometimes be 33, but if so you've
been counting the highest bit, which doesn't count.

The polynomial for CRC-16 is sometimes given as @math{x^{16} + x^{15}
+ x^2 + 1}. This translates to @code{#b1000000000000101}
(@code{#x8005}). Notice that @math{x^{16}} is absent. Don't use the
reversed polynomial if you have one of those, instead set @var{ref-in}
and @var{ref-out} properly.

After a CRC has been calculated it is sometimes XOR'd with a final
value, this is @var{xor-out}.

@var{check} is either @code{#f} or the CRC of the string @code{"123456789"}.
@end deffn

@deffn Syntax define-crc name (coefficients ...) init ref-in ref-out xor-out check
This is a slightly easier version of the advanced interface where you
can simply specify the powers of the coefficients. CRC-16 in this
syntax becomes:

@example
(import (weinholt crypto crc))
(define-crc crc-16 (16 15 2 0) #x0000 #t #t #x0000 #xBB3D)
@expansion{}
(begin
  (define (crc-16 bv)
    (crc-16-finish (crc-16-update (crc-16-init) bv)))
  (define (crc-16-init) #x0000)
  (define (crc-16-finish r) (bitwise-xor r #x0000))
  (define (crc-16-self-test)
    (if #xBB3D
        (if (= (crc-16 (string->utf8 "123456789")) #xBB3D)
            'success 'failure)
        'no-self-test))
  @dots{})
@end example

Another example: the polynomial @math{x^8 + x^2 + x + 1} in this syntax
is @code{(8 2 1 0)}.
@end deffn

After e.g.@: @code{(define-crc crc-32)} has been used, these bindings
will be available (with names that match the name of the CRC):

@deffn Procedure crc-32 bytevector
Calculates the final CRC of the entire bytevector and returns it as an
integer.

@example
(import (weinholt crypto crc))
(define-crc crc-32)
(crc-32 (string->utf8 "A fiendish scheme"))
@result{} 1384349758
@end example
@end deffn

@deffn Procedure crc-32-init
Returns an initial CRC state.
@end deffn

@deffn Procedure crc-32-update state bv [start end]
Uses the @var{state} and returns a new state that includes the CRC of
the given bytes.

@example
(import (weinholt crypto crc))
(define-crc crc-32)
(crc-32-finish
 (crc-32-update (crc-32-init)
                (string->utf8 "A fiendish scheme")))
@result{} 1384349758
@end example
@end deffn

@deffn Procedure crc-32-finish state
Finalizes the CRC @var{state}.
@end deffn

@deffn Procedure crc-32-width
Returns the bit-width of the CRC, e.g.@: 32 for CRC-32.
@end deffn

@deffn Procedure crc-32-self-test
Performs a sanity check and returns either
@code{success}, @code{failure} or @code{no-self-test}.
@end deffn

@noindent
Version history:
@itemize
@item
@code{(1 0)} -- Initial version. Includes crc-32, crc-16,
 crc-16/ccitt, crc-32c, and crc-24.
@item
@code{(1 1)} -- Added crc-64 and the @code{-width} procedures. The
@code{-update} procedures use fixnums if @code{(fixnum-width)} is
larger than the CRC's width.
@end itemize

@c ======================================================================
@node crypto des
@subsection Data Encryption Standard
The Data Encryption Standard (DES) is older than AES and uses shorter
keys. To get longer keys the Triple Data Encryption Algorithm (TDEA,
3DES) is commonly used instead of DES alone.
@cindex Triple Data Encryption Algorithm
@cindex 3DES


The @code{(weinholt crypto des)} library is incredibly inefficient and
the API is, for no good reason, different from the AES library. You
should probably use AES instead, if possible.

@deffn Procedure des-key-bad-parity? key
Returns @code{#f} if the DES @var{key} has good parity, or the index
of the first bad byte. Each byte of the @var{key} has one parity bit,
so even though it is a bytevector of length eight (64 bits), only 56
bits are used for encryption and decryption. Parity is usually
ignored.
@end deffn

@deffn Procedure des! bv key-schedule [offset E]
The fundamental DES procedure, which performs both encryption and
decryption in Electronic Code Book (ECB) mode. The eight bytes
starting at @var{offset} in the bytevector @var{bv} are modified
in-place.

The @var{offset} can be omitted, in which case 0 is used.

The @var{E} argument will normally be omitted. It is only used by the
@code{des-crypt} procedure.

@example
(import (weinholt crypto des))
(let ((buf (string->utf8 "security"))
      (sched (permute-key (string->utf8 "terrible"))))
  (des! buf sched)
  buf)
@result{} #vu8(106 72 113 111 248 178 225 208)
@end example

@example
(import (weinholt crypto des))
(let ((buf (bytevector-copy #vu8(106 72 113 111 248 178 225 208)))
      (sched (reverse (permute-key (string->utf8 "terrible")))))
  (des! buf sched)
  (utf8->string buf))
@result{} "security"
@end example

@end deffn

@deffn Procedure permute-key key
Permutes the DES @var{key} into a key schedule. The key schedule is
then used as an argument to @code{des!}. To decrypt, simply reverse
the key schedule. The return value is a list.
@end deffn

@deffn Procedure tdea-permute-key key1 [key2 key3]
Permutes a 3DES key into a key schedule. If only one argument is given
then it must be a bytevector of length 24. If three arguments are given
they must all be bytevectors of length eight.

The return value's type is unspecified.
@end deffn

@deffn Procedure tdea-encipher! bv offset key
Encrypts the eight bytes at @var{offset} of @var{bv} using the given
3DES key schedule.
@end deffn

@deffn Procedure tdea-decipher! bv offset key
The inverse of @code{tdea-encipher!}.
@end deffn

@deffn Procedure tdea-cbc-encipher! bv key iv offset count
Encrypts the @var{count} bytes at @var{offset} of @var{bv} using
Cipher Block Chaining (CBC) mode.

The @var{iv} argument is the @dfn{Initial Vector}, which is XOR'd with
the data before encryption. It is a bytevector of length eight and it
is modified for each block.

Both @var{offset} and @var{count} must be a multiples of eight.
@end deffn

@deffn Procedure tdea-cbc-decipher! bv key iv offset count
The inverse of @code{tdea-cbc-encipher!}.
@end deffn

@deffn Procedure des-crypt password salt
This is a password hashing algorithm that used to be very popular on
Unix systems, but is today too fast (which means brute forcing
passwords from hashes is fast). The @var{password} string is at most
eight characters.

The algorithm is based on 25 rounds of a slightly modified DES.

The @var{salt} must be a string of two characters from the alphabet
@code{#\A}--@code{#\Z}, @code{#\a}--@code{#\z},
@code{#\0}--@code{#\9}, @code{#\.} and @code{#\/}.

@example
(import (weinholt crypto des))
(des-crypt "password" "4t")
@result{} "4tQSEW3lEnOio"
@end example

A more general interface is also available, @pxref{crypto password}.
@end deffn


@noindent
Version history:
@itemize
@item
@code{(1 0)} -- Initial version.
@end itemize


@c ======================================================================
@node crypto dsa
@subsection Digital Signature Algorithm
The @code{(weinholt crypto dsa)} library provides procedures for
creating and verifying DSA signatures. DSA is a public key signature
algorithm, which means that it uses private and public key pairs. With
a private key you can create a signature that can then be verified by
someone using the corresponding public key. The idea is that it's very
difficult to create a correct signature without having access to the
private key, so if the signature can be verified it must have been
made by someone who has access to the private key.

DSA is standardized by FIPS Publication 186. It is available at this
web site: @url{http://csrc.nist.gov/publications/PubsFIPS.html}.

There is currently no procedure to generate a new DSA key. Here is
how to generate keys with OpenSSL or GnuTLS:
@verbatim
openssl dsaparam 1024 | openssl gendsa /dev/stdin > dsa.pem
certtool --dsa --bits 1024 -p > dsa.pem
@end verbatim

The key can then be loaded with @code{dsa-private-key-from-pem-file}.

@deffn Procedure make-dsa-public-key p q g y
Returns a DSA public key value. See the FIPS standard for a
description of the parameters.

To access the fields use @code{dsa-public-key-p},
@code{dsa-public-key-q}, @code{dsa-public-key-g} and
@code{dsa-public-key-y}.
@end deffn

@deffn Procedure dsa-public-key? obj
Returns @code{#t} if @var{obj} is a DSA public key value.
@end deffn

@deffn Procedure make-dsa-private-key p q g y x
Returns a DSA private key value. See the FIPS standard for a
description of the parameters.

To access the fields use @code{dsa-private-key-p},
@code{dsa-private-key-q}, @code{dsa-private-key-g},
@code{dsa-private-key-y} and @code{dsa-private-key-x}.
@end deffn

@deffn Procedure dsa-private-key? obj
Returns @code{#t} if @var{obj} is a DSA private key.
@end deffn

@deffn Procedure dsa-private->public private-key
Converts a private DSA key into a public DSA key by removing the
private fields.
@end deffn

@deffn Procedure dsa-private-key-from-bytevector bv
Parses @var{bv} as an ASN.1 DER encoded private DSA key.
@end deffn

@deffn Procedure dsa-private-key-from-pem-file filename
Opens the file and reads a private DSA key. The file should be in
Privacy Enhanced Mail (PEM) format and contain an ASN.1 DER encoded
private DSA key.
@end deffn

@deffn Procedure dsa-create-signature hash private-key
The @var{hash} is the message digest (as a bytevector) of the data you
want to sign. The @var{hash} and the @var{private-key} are used to
create a signature which is returned as two values: @code{r} and
@code{s}.

The @var{hash} can e.g.@: be an SHA-1 message digest. Such a digest is
160 bits and the @var{q} parameter should then be 160 bits.
@end deffn

@deffn Procedure dsa-verify-signature hash public-key r s
The @var{hash} is the message digest (as a bytevector) of the data
which the signature is signing.

Returns @code{#t} if the signature matches, otherwise @code{#f}.
@end deffn

@noindent
Version history:
@itemize
@item
@code{(0 0)} -- Initial version.
@end itemize



@c ======================================================================
@node crypto md5
@subsection Message-Digest algorithm 5
The @code{(weinholt crypto md5)} library is an implementation of the
cryptographic hash function MD5. It takes bytes as input and returns a
@dfn{message digest}, which is like a one-way summary of the data. The
idea is that even the smallest change in the data should produce a
completely different digest, and it should be difficult to find
different data that has the same digest. An MD5 digest is 16 bytes.

MD5 has a maximum message size of @math{2^{64}-1} bits.

The MD5 algorithm is considered broken and you will likely want to use
SHA-2 instead, if possible.

@deffn Procedure md5 bv ...
The complete all-in-one procedure to calculate the MD5 message digest
of all the given bytevectors in order. Returns an md5 state, which
should be used with @code{md5->bytevector} or @code{md5->string}.

@example
(md5->string (md5 (string->utf8 "A Scheme in my pocket")))
@result{} "65A2B2D8EE076250EA0A105A8D5EF1BB"
@end example
@end deffn

@deffn Procedure make-md5
Returns a new MD5 state for use with the procedures below. The type of
the return value is unspecified.
@end deffn

@deffn Procedure md5-update! md5state bv [start end]
Updates the @var{md5state} to include the specified range of data from
@var{bv}.
@end deffn

@deffn Procedure md5-finish! md5state
Finalizes the @var{md5state}. This must be used after the last call to
@code{md5-update!}.
@end deffn

@deffn Procedure md5-clear! md5state
Clear the @var{md5state} so that it does not contain any part of the
input data or the message digest.
@end deffn

@deffn Procedure md5-copy md5state
Make a copy of the @var{md5state}.
@end deffn

@deffn Procedure md5-finish md5state
Performs @code{md5-finish!} on a copy of @var{md5state} and then
returns the new state.
@end deffn

@deffn Procedure md5-copy-hash! md5state bv offset
Copies the message digest (a.k.a.@: hash) in the finalized
@var{md5state} into @var{bv} at the given offset.
@end deffn

@deffn Procedure md5->bytevector md5state
Returns a new bytevector which contains a binary representation of the
finalized @var{md5state}.
@end deffn

@deffn Procedure md5->string md5state
Returns a new string which contains a textual representation of the
finalized @var{md5state}. The conventional hexadecimal representation
is used.
@end deffn

@deffn Procedure hmac-md5 secret bytevector ...
An HMAC is a Hash-based Message Authentication Code. This procedure uses
MD5 to generate such a code. The return value is an MD5 state.
@end deffn

@noindent
Version history:
@itemize
@item
@code{(1 0)} -- Initial version.
@end itemize

@c ======================================================================
@node crypto password
@subsection Password hashing
The procedure provided by @code{(weinholt crypto password)} is the
same type of procedure that is called @code{crypt} in the standard C
library. It is used for password hashing, i.e.@: it scrambles
passwords. This is a method often used when passwords need to be
stored in databases.

The scrambling algorithms are based on cryptographic primitives but
have been modified so that they take more time to compute. They also
happen to be quite annoying to implement.

Only DES and MD5 based hashes are currently supported.

@deffn Procedure crypt password salt
Scrambles a @var{password} using the given @var{salt}. The @var{salt}
can also be a hash. The returned hash will be prefixed by the salt.

A fresh random salt should be used when hashing a new password. The
purpose of the salt is to make it infeasible to reverse the hash
using lookup tables.

To verify that a password matches a hash, you can do something like
@code{(string=? hash (crypt password hash))}.

@example
(import (weinholt crypto password))
(crypt "test" "..")
@result{} "..9sjyf8zL76k"
@end example

@example
(crypt "test" "$1$RQ3YWMJd$")
@result{} "$1$RQ3YWMJd$oIomUD5DCxenAs2icezcn."
@end example

@example
(string=? "$1$ggKHY.Dz$fNBcmNFTa1BFGXoLsRDkS."
          (crypt "test" "$1$ggKHY.Dz$fNBcmNFTa1BFGXoLsRDkS."))
@result{} #t
@end example
@end deffn

@c TODO: there ought be a simple way to generate a fresh salt

@noindent
Version history:
@itemize
@item
@code{(1 0)} -- Initial version.
@end itemize

@c ======================================================================
@node crypto sha-1
@subsection Secure Hash Algorithm 1
The interface provided by @code{(weinholt crypto sha-1)} is identical
to the one provided by the MD5 library, except every procedure is
prefixed by @code{sha-1} instead of @code{md5}. @xref{crypto md5}.

SHA-1 also has a maximum message size of @math{2^{64}-1} bits, but
the message digests are 160 bits instead of 128.
@cindex SHA-1

@noindent
Version history:
@itemize
@item
@code{(1 0)} -- Initial version.
@end itemize

@c ======================================================================
@node crypto sha-2
@subsection Secure Hash Algorithm 2
The interface provided by @code{(weinholt crypto sha-2)} is identical
to the one provided by the MD5 library, but instead of @code{md5},
every procedure is prefixed by @code{sha-224}, @code{sha-256},
@code{sha-384} or @code{sha-512}. @xref{crypto md5}.

SHA-224 and SHA-256 have a maximum message size of @math{2^{64}-1}
bits. For SHA-384 and SHA-512 the maximum is @math{2^{128}-1} bits.
The message digests produced by SHA-224 are 224 bits, and so on.
@cindex SHA-224
@cindex SHA-256
@cindex SHA-384
@cindex SHA-512

@noindent
Version history:
@itemize
@item
@code{(0 0)} -- Initial version.
@end itemize
